---
services:
  monitor:
    image: ghcr.io/genzj/phone-monitor:latest
    environment:
      - "TZ=America/New_York"
    env_file:
      - path: stack.env
        required: false
    container_name: "${COMPOSE_PROJECT_NAME}-monitor"

  ofelia:
    image: mcuadros/ofelia:latest
    environment:
      - "TZ=America/New_York"
    restart: unless-stopped
    command: "daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.monitor.schedule: "@every 5m"
      ofelia.job-run.monitor.container: "${COMPOSE_PROJECT_NAME}-monitor"
